services:
  ngrok:
    image: ngrok/ngrok:3
    ports:
      - "4040:4040"
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./docker/ngrok.yml:/etc/ngrok.yml